### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hakiri** [nokia/vscode-ttcn3#11]
- Issue Type: `Performance`
- Extension Name: `ttcn3`
- Extension Version: `0.2.0`
- OS Version: `Windows_NT x64 10.0.21343`
- VS Code version: `1.55.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`%Appdata%\Local\Temp\Nokia.ttcn3-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by 5nord** [comment]
The extension delegates most work to a background process (called [language server](https://github.com/nokia/ntt)). It makes me wonder how it's possible to cause any high CPU load.

Unfortunately I cannot reproduce your scenario. Do you happen to have mentioned file `Nokia.ttcn3-unresponsive.cpuprofile.txt`? Or maybe you could help me recreating the environment for the high CPU load?
