### ISSUE TITLE
Install missing tool

### ISSUE THREAD

**Issue by 5nord** [nokia/vscode-ttcn3#3]
Installing missing tools like k3 language server would greatly improve user experience.

**Comment by mak3** [comment]
I'm not familiar with Go.
After executing command "go get -u github.com/nokia/ntt/cmd/...", do I need to do something else?
Files were downloaded to /home/user/go/src/github.com/nokia/ntt

I don't think "k3" command is available anywhere in the system (Ubuntu 20.04)

In VSCode it looks like:
> [Error - 2:01:25 AM] Starting client failed
> Launching server using command k3 failed.

**Comment by 5nord** [comment]
I am currently updating README and contribution guide to provide better install instructions. Until then you'll probably find the k3 command in `/home/user/go/bin/`.

I think I further should make the k3 command optional and configurable. So you can disable language-server, if you find it to unstable.

**Comment by 5nord** [comment]
The newest release has k3 disabled by default.

**Comment by Crystal0000** [comment]
How to enable the search function for TTCN-3 lanuage? I installed the plugin but Jump to definition function is not avaiable, is there some way to continue?

Jump to Definition (when TTCN-3 Language Server is enabled).

**Language Server
TTCN-3 support is powered by the NTT/K3 Language Server. It's still very much in beta and therefore disabled by default. If you want to try it out, install k3 tool somewhere, so this extension can find it.

Set ttcn3.useLanguageServer to true to enable the use of language server and reload the extension.**

**Comment by Crystal0000** [comment]
> experience

How to install K3 lanuage server?

**Comment by 5nord** [comment]
Some variants how to install the TTCN-3 language server are described [here](https://github.com/nokia/ntt#install). Kindly note `ntt` and `k3` are interchangeable (k3 is just the closed source predecessor of ntt). I am also improving documentation details on how to install and use the language server. But, I'll probably require another week to finish.

BTW, in January I'll will implement auto-install feature for this extension, so people don't need to install the language server manually.
