### ISSUE TITLE
Downloading ntt language server does not work

### ISSUE THREAD

**Issue by adoebber** [nokia/vscode-ttcn3#47]
The automatic download of the ntt language server does not seem to work. The status bar shows that something is happening, but even after several minutes nothing happens. Unfortunately, I cannot reproduce the problem because I now get GitHub rate limit errors.

After installing the language server manually, the log says: "Installed TTCN-3 Language Server version: 0.0.0". I installed version 0.18.0. The rest works fine. The wrong version number will trigger the update check on every start of VSCode (assuming there is no GitHub rate limit).

I can turn off automatic updating. So this is not a big issue for me.

I have tested the extension 0.8.0 on Windows 11.

**Comment by 5nord** [comment]
I could reproduce this issue using my Linux machine behind a proxy.

I am preparing a release that has proxy support and no GitHub rate limit issue. It will take me a few days, probably.

**Comment by 5nord** [comment]
The [new version](https://github.com/nokia/vscode-ttcn3/releases/tag/v0.10.0) of this extension should fix various download issues. For three reasons:
* you don't need to download additional binaries, because ntt is now bundled.
* the new request package has better support for proxies, redirects, ...
* custom update server URLs prevent GitHub rate limiting issues.

**Comment by adoebber** [comment]
Thanks very much for your fix. Unfortunately it does not work for me:
```
Could not update TTCN-3 Language Server: Error: Missing asset URL from https://ttcn3.dev/api/v1/ntt: ntt_windows_x86_64.tar.gz
```
I get a 404 error for "https://ttcn3.dev/api/v1/ntt".

**Comment by adoebber** [comment]
Now it works (I changed nothing). Thanks!!

**Comment by 5nord** [comment]
I thank you! Without your help I would not have found these issues.
